apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2lte
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-plhn-tenant/rhtap-demo-app/hacbs-test-project-2lte@sha256:36ef117a310602a757112fcd4cb18aae4dad0fb035eed3005983f7b210ea9a1a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
