apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2lte
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-plhn-tenant/rhtap-demo-app/hacbs-test-project-2lte@sha256:64b24d49821224f092967e8d7465a738c1acc8e861663b32aac85165ea43bcdc
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
